# Generated by Django 5.2.10 on 2026-01-18 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(editable=False, help_text='Número identificador da Ordem de Serviço', max_length=20, unique=True)),
                ('defeito', models.TextField(help_text='Defeito informado pelo cliente')),
                ('observacoes', models.TextField(blank=True, help_text='Observações técnicas do serviço')),
                ('status', models.CharField(choices=[('AG_ORC', 'Aguardando orçamento'), ('AG_APR', 'Aguardando aprovação'), ('AG_CON', 'Aguardando conserto'), ('FINAL', 'Finalizado'), ('ENTREG', 'Entregue')], default='AG_ORC', max_length=6)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente')),
            ],
        ),
    ]
