# Generated by Django 5.2.10 on 2026-02-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='modelo_equipamento',
            field=models.CharField(blank=True, help_text='Modelo ou versão do equipamento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='nome_equipamento',
            field=models.CharField(blank=True, help_text='Ex: Playstation 5, Xbox Series X', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
