# Generated by Django 5.2.10 on 2026-02-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do serviço. Ex: Rebbaling', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do serviço')),
                ('preco_base', models.DecimalField(decimal_places=2, help_text='Preço padrão do serviço', max_digits=10)),
                ('ativo', models.BooleanField(default=True, help_text='Defina se o serviço está disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['nome'],
            },
        ),
    ]
