# Generated by Django 5.2.10 on 2026-02-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição do serviço realizado')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor referente a esse serviço', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_executados', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Serviço Executado',
                'verbose_name_plural': 'Serviços Executados',
            },
        ),
    ]
