# Generated by Django 5.2.10 on 2026-02-04 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_ordemservico_modelo_equipamento_and_more'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoExecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, help_text='Valor cobrado por este serviço', max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_executados', to='ordens.ordemservico')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Serviço Executado',
                'verbose_name_plural': 'Serviços Executados',
            },
        ),
    ]
