# Generated by Django 5.2.10 on 2026-02-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_servicos/')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicos.servicoexecutado')),
            ],
        ),
    ]
