# Generated by Django 5.2.10 on 2026-01-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do cliente ou razão social', max_length=100)),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', help_text='Defina se o cliente é pessoa física ou jurídica', max_length=2)),
                ('documento', models.CharField(help_text='CPF ou CNPJ do cliente', max_length=18, unique=True)),
                ('telefone', models.CharField(help_text='Telefone principal para contato', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
